## UniFlex Agent config file

config:
  name: "RRM_Simple_Controller"
  info: 'agent hosts global RRM controller'
  iface: 'lo'
##  type: 'slave'
##  iface: 'ens33'
  sub: "tcp://10.5.0.2:8990"
  pub: "tcp://10.5.0.2:8989"

#broker:
#  xpub: "tcp://127.0.0.1:8990"
#  xsub: "tcp://127.0.0.1:8989"

control_applications:
  myController:
      file : rrm_controller.py
      class_name : RRMController
      kwargs : {}
  discovery:
      module : uniflex_app_discovery_pyre
      class_name : PyreDiscoverySlaveModule
      kwargs: { "iface":"lo", "groupName":"uniflex_1234" }
